name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish Project
      run: dotnet publish NotebookApp/NotebookApp.csproj -c Release -o release

    - name: Fix Blazor Routing for GitHub Pages
      run: |
        cp release/wwwroot/index.html release/wwwroot/404.html
        sed -i 's|<head>|<head><script type="text/javascript">\(function(l){if(l.search[0]==="?"){var r={};l.search.slice(1).split("\&").forEach(function(v){var a=v.split("=");r[a[0]]=a.slice(1).join("=")});if(r.p!==undefined){window.history.replaceState(null,null,l.pathname.slice(0,-1)+(r.p||"")+(r.q?"?"+r.q:"")+l.hash)}}}(window.location))</script>|' release/wwwroot/index.html
        sed -i 's|<head>|<head><script type="text/javascript">\(function(l){if(l.search==="") {var p=l.pathname.replace('\''/'${{ github.event.repository.name }}'\'' , '\'''\'');window.location.replace(l.protocol+"//"+l.hostname+(l.port?":"+l.port:"")+l.pathname.slice(0,l.pathname.length-p.length)+"/?p="+p.replace(/\//g,"%2F"))}}(window.location))</script>|' release/wwwroot/404.html

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: release/wwwroot

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
